version: '3.8'

services:
  # MongoDB service
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - app-network
    environment:
      - MONGO_INITDB_DATABASE=curso_coaching_ontologico

  # Backend service for development
  backend-dev:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend-dev
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    environment:
      - PORT=5000
      - MONGODB_URI=mongodb://mongodb:27017/curso_coaching_ontologico
      - JWT_SECRET=curso_coaching_ontologico_secret_key_2025
      - NODE_ENV=development
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - app-network
    command: npm run dev

  # Frontend service for development
  frontend-dev:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: frontend-dev
    restart: always
    ports:
      - "3000:5173"
    depends_on:
      - backend-dev
    environment:
      - VITE_API_URL=http://localhost:5000/api
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - app-network
    command: npm run dev

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data:
